### ISSUE TITLE
How to rectify the error "Lost atoms: original 28437 current 3659" in LAMMPS?

### ISSUE THREAD

**Issue by saismaransb** [HPQC-LABS/QCBugs#18]
[See my full question on the Modeling Matters Stack Exchange](https://mattermodeling.stackexchange.com/questions/1380/how-to-rectify-the-error-lost-atoms-original-28437-current-3659-in-lammps).

**Comment by ducryf** [comment]
@saismaransb Is the issue fixed or do you need further help?

**Comment by saismaransb** [comment]
The code runs smoothly, but as I observed the dumpfile animations in OVITO the nano cone does not indent the protein at all. 
I have recorded a video of it and I would like to share it with you. How can I share it with you?

**Comment by ducryf** [comment]
@saismaransb If the "Lost atoms" problem is fixed you should close this issue. What you describe here is an entirely different problem now which could have dozens of origins. Are you sure that the force field parameters you use describe the system well? Does the cone without the protein behave as expected? Does the protein without the cone behave as expected? Are the region commands applied correctly? You should make the simulation as small as possible and only increase the complexity bit by bit.

**Comment by saismaransb** [comment]
Yes. I am sorry I got caught up in the issue too much. Yes, with your help i can now close this issue. 
Although, I am now debugging the code line by line, I shall open an issue on stack exchange and close this here. 
I think the "region" commands are at fault any way I'll check them. Anyway thanks for the help. And yes,  the cone and the protein behave exactly as it should individually!
